name: Deploy to Production
on:
  push:
    branches:
      - production

env:
  REACT_APP_API_ENDPOINT: ${{ secrets.PROD_API_ENDPOINT }}
  REACT_APP_NODE_ENV: "production"
  NODE_ENV: "production"
  REACT_APP_BASE_URL: ${{ secrets.PROD_BASE_URL }}
  REACT_APP_CELO_ENDPOINT: ${{ secrets.PROD_CELO_ENDPOINT }}
  REACT_APP_API_SECRET: ${{ secrets.PROD_API_SECRET }}
  REACT_APP_CELO_SINK: ${{ secrets.PROD_CELO_SINK }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install firebase tools
        run: |
          sudo npm install -g firebase-tools
          firebase use bitmama-prod --token ${{ secrets.PROD_FIREBASE_TOKEN }}

      - name: Build webapp
        run: |
          npm install
          npm run build

      - name: Deploy to production site
        if: github.ref == 'refs/heads/production'
        run: firebase deploy --only hosting:prod-valora --non-interactive --token ${{ secrets.PROD_FIREBASE_TOKEN }} -m "RunID ${{ github.run_id }} Commit SHA ${{ github.sha }}"